title: Predicting Urban Expansion in US Cities Using Machine Learning
logo: /assets/img/
description: Saiya Sheth & Tiffany M. Tran
show_downloads: false
repository: tfmtran/urban-expansion
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
